
# Preface {-}

## Course Info {-}

- Course Number: DVM 523
- Course Title: Veterinary Parasitology
- Year: Fall 2021



This course reviews common helminth parasites (nematodes, trematodes, cestodes, acanthocephalans), protozoan and arthropod parasites commonly found in domestic species. The course will also integrate with practical courses delivered during the semester.

---

**Prerequisite**

Enrollment in semester 3 of the DVM program


## Instructor Info {-}

My name is Pratap Kafle. You can call me by my first name (Pratap) or Dr. Kafle, or Prof. Kafle, whatever you like!

I am a veterinarian by training and I received my specialization in Parasitology during my graduate study and professional work in Canada. I completed my DVM in 2011 and practiced as a mixed animal veterinarian for almost 2 years in Nepal before moving to Canada to pursue graduate studies. I completed my PhD in 2018 from University of Calgary, specializing in parasitology, disease ecology and modelling. For my PhD research I studied the ecology of host-parasite interaction using the unique system of arctic ungulate (host) and their protostrongylid nematodes (parasites) in the Canadian Arctic. My postdoctoral work at the University of Calgary and University of Saskatchewan involved studying a variety of parasites of wildlife, pets and humans and researching Coronaviruses (including SARS-CoV-2) in Canadian wildlife. I was also a co-instructor of the veterinary parasitology course in the Western College of Veterinary Medicine at the University of Saskatchewan.

If you are interested to know more about my research, here is the list of my [publications](https://www.researchgate.net/profile/Pratap_Kafle/publications.)

I am pretty excited to be here and I look forward to working together with you all to make this course a great learning experience.

<br />
<br />

**Where to find me?**

You can email me anytime at Pratap.Kafle@liu.edu or call me at my office phone +1 516 200 2805. I will try my best to respond to your queries during the office hours. Although I will try to respond your emails during weekend/holidays, I can't guarantee as I have a pretty young family and I like to spend my weekends and holidays with my family.

My office is located in the 2nd floor of Roth Hall, Room 209. Although I recommending sending me an email beforehand, please feel free to stop by my office anytime if you have any questions. Parasitology research lab is located in the Life sciences building (Room: LS14) and I hope to make it functional in a year or so.

My office is located

```{r echo=FALSE}
library(leaflet)
library(webshot)

leaflet() %>%
    addTiles() %>%
    setView(lng = -73.59535, lat = 40.82067, zoom = 50)
```


## Curricular Endpoints {-}

- PCC1. Demonstrate knowledge and understanding of the central biological principles and mechanisms that underlie animal health and disease from the molecular and cellular level to organismal and population manifestations.

- PCC2. Demonstrate understanding of normal structure, function, homeostasis, pathophysiology, mechanisms of health/disease, and the natural history and manifestations of important domestic and global animal diseases in a diverse society.

- CC1a. Demonstrate ability to perform comprehensive patient diagnosis and utilize problem solving skills to analyze a patient and develop a list of differential diagnoses.

- CC1b. Demonstrate ability to perform comprehensive patient diagnosis and utilize problem solving skills to develop disease prevention strategies, therapeutic intervention plans, and/or biosecurity measures involving diseases of individual animals and populations.

- CC1c. Demonstrate ability to perform comprehensive patient diagnosis and utilize problem solving skills to select, utilize, interpret and synthesize relevant physical and laboratory diagnostic procedures including diagnostic imaging and diagnostic pathology.

- CC3. Demonstrate ability to apply acquired knowledge in managing anesthesia, pain, and patient welfare.

- CC7. Demonstrate ability to identify ways to prevent disease, identify organisms that require biosecurity measures, identify zoonotic disease and food safety issues and to promote awareness of the contributions of the veterinary profession to the overall public and professional healthcare teams.

- CC8a. Demonstrate effective skills in client communications and ethical conduct as it relates to how to acquire information from clients (e.g. history) and about patients (e.g. medical records), to obtain, store and retrieve such information, and to communicate effectively with a diverse population of clients and colleagues.

- CC8b. Demonstrate ethical conduct and understanding of professional ethics, influences of different cultures on the delivery of veterinary medical services to the public.

- CC8c. Demonstrate knowledge, skills, values, attitudes, aptitude and behaviors necessary to address responsibly the health and well-being of animals in the context of the societal responsibilities of veterinarians and ever-changing societal expectations.

- CC8d. Demonstrate basic knowledge of personal and small business management and awareness of the different career options in Veterinary Medicine.

- CC9. Demonstrate solid knowledge of the role of research in furthering the practice of Veterinary Medicine.



## Learning Objectives {-}

1. Identify common helminth, protozoan and arthropod parasites found in domestic species

2. Describe the developmental life cycles of common helminth, protozoan and arthropod parasites found in domestic species

3. Interpret basic diagnostic procedures used in veterinary parasitology

4. Integrate knowledge and skills acquired in this course with cases observed in local veterinary practices

5. Utilize veterinary terminology commonly used in parasitology
