# Parasitism and parasitology {-}

On earth, many organisms live together in varied intricate relationships, either temporarily or permanently. The common term for this relationship between organism is SYMBOSIS (Sam meaning “together” and bioses meaning “living” ). Each member of the association is called a symbiont.

There are five types of symbiotic relationships:

1. Predator-prey : 
	⁃	One species (predator) benefits at the expense of the other (prey)
	⁃	Extremely short-term relationship
	⁃	Eg: Lion and Zebra - Lion (predator) kills zebra (prey) for food. 
	
2. Phoresis (phore meaning “to carry”):
	⁃	Smallest member is mechanically carried about by the larger member
	⁃	E.g.: 
	
3. Mutualism:
	⁃	Each species dependent on the other for their mutual well-being and survival (e.g. cellulose-digesting organisms in the caecum of a horse).
	
4. Commensalism: 
	⁃	One symbiont benefits and the other is neither benefited nor harmed.
	⁃	E.g: 
	
5. Parasitism
Parasitism is the mode of existence in which one organism, the parasite, infects another, the host, and the parasite does some measure of harm to the host while itself deriving a benefit. Parasitism is one of the most common lifestyles on earth.

Parasitism is part of a spectrum of intimate zoological relationships between unrelated organisms
The features of this ecological relationship are:[^1]

- the parasite is physiologically dependent on the host; 
- the infection process produces or tends to produce an over-dispersed distribution of parasites within the host population; 
- the parasite kills heavily infected hosts; 
- the parasite species has a higher reproductive potential than the host species.

**Parasitism can occur in varying degrees**

- Parasitiasis: 

Parasite within the host is potentially harmful but the host doesn’t show obvious clinical signs of the disease. E.g : Cattle on pasture may carry trichrongyles (roundworms) without showing any clinical signs

- Parasitosis: 
Parasite produce obvious harm/injury to the host manifested by clinical signs
E.g.: Emaciated cow on pasture certainly carries roundworms.


[^1] R.M. Anderson and R.M. May (1978) Regulation and stability in hostparasite
population interactions I Regulatory processes. Journal of Animal
Ecology 47, 219-247.


## Parasitology {-}

Parasitology is the study of parasitism; a multidisciplinary subject encompassing many topics including morphology, taxonomy, biology, behaviour, life-cycles, pathogenesis, epidemiology, ecology, physiology, biochemistry, genetics and molecular biology, as well as the diagnosis, immunology and treatment of parasitic infections.

## why should we study parasitology? {-}

The field of veterinary parasitology has important implications for human and animal health. Parasites remain the major cause of numerous clinical and subclinical diseases in humans, domestic animals, wildlife often resulting in loss of lives and productivity.  Hence, parasites can cause tremendous economic loss, and greatly impede the economic development of some countries, especially in the tropics. 

We must study parasites because parasites are:

- Causative agents of numerous diseases
- Vectors of infectious agents
- Causative ages of zoonoses
- Problems in food hygiene
- Impact trade
- Animal welfare
- Economic factors

To do anything about this requires deep knowledge of parasite life cycles, modes of infection, immunology, pathogenesis, and other facets of their biology.

It's estimated that at least half of all known species are parasitic, so understanding the life cycle and interaction of these organisms with their hosts is often key to understanding the dynamics of ecosystems generally.

Parasites are fascinating organisms in their anatomy, physiology, and behavior, and we can learn a lot about life in general by studying them from a biological perspective even parasites that have no impact on the health of humans or the animals we care about.

Nearly 40% of the species on earth are parasitic of some kind. Parasites are often overlooked in trophic interactions but they represent the major share of all trophic interactions. They have the ability to shape community structure through their effects on trophic interactions, food webs, competition, biodiversity, and keystone species.[^2] 


[^2] https://www.nature.com/scitable/knowledge/library/ecological-consequences-of-parasitism-13255694/
